export const stylesBasketDark = {
    container:{
        backgroundColor:'#151515'
    },
    tab:{
        color:"#fff"
    },
    sum:{
        color:"#fff"
    },
    callText:{
        color:"#fff"
    },
    infoText:{
        color:"#fff"        
    },
    infoInput:{
        color:"#fff",        
    },
    submitText:{
        color:"#fff"
    }
}