export const stylesBasketWeb = {
    container:{
        width:"100%", 
        height:"100%", 
        overflow:"scroll",
    },
    tab:{
        fontWeight:600, 
        fontSize:24, 
        marginLeft:'auto',
        marginRight:'auto',
        marginTop:32
    },
    sum:{
        fontWeight:400, 
        fontSize:16, 
        marginLeft:'auto',
        marginRight:'auto',
    },
    call:{
        width:210, 
        height:48, 
        marginTop:24,
        marginLeft:'auto',
        marginRight:'auto',
        justifyContent:'center',
        alignItems:'center'
    },
    callText:{
        fontWeight:600, 
        fontSize:14
    },
    params:{
        width:533,
        height:218,
        marginTop:16,
        marginLeft:'auto',
        marginRight:'auto',
        
        display:"flex",
        flexDirection:"column",
        flexWrap:"wrap",
        alignContent:"space-around",
        justifyContent:"space-between",
        alignItems:'center'
    },
    infoText:{
        fontWeight:400, 
        fontSize:14
    },
    infoInput:{
        width:256,
        marginTop:2,
        height:48,
        borderRadius:10,
        borderWidth:2,
        paddingLeft:16
    },
    submit:{
        height:48,
        width:256,
        borderRadius:10,
        borderWidth:2,
        borderColor:"#ff7a00",
        display:"flex",
        alignItems:"center",
        justifyContent:"center"
    },
    submitText:{
        fontWeight:600, 
        fontSize:14
    }
}