export const stylesBasketDark = {
    container:{
        backgroundColor:'#151515'
    },
    tab:{
        color:"#fff"
    },
    sum:{
        color:"#fff"
    },
    call:{
        backgroundColor:"#1c1c1c"
    },
    callText:{
        color:"#fff"
    },
    infoText:{
        color:"#fff"        
    },
    infoInput:{
        borderColor:"#bbb",
        backgroundColor:"#1c1c1c",
        color:"#fff",        
    },
    submit:{
        backgroundColor:"#1c1c1c",        
    },
    submitText:{
        color:"#fff"
    }
}