export const stylesBasketWhite = {
    container:{
        backgroundColor:"#fff"
    },
    tab:{
        color:"#1c1c1c"
    },
    sum:{
        color:"#1c1c1c"
    },
    callText:{
        color:"#1c1c1c"
    },
    infoText:{
        color:"#1c1c1c"        
    },
    infoInput:{
        color:"#1c1c1c"        
    },
    submitText:{
        color:"#1c1c1c"
    }
}