export const stylesFooter = {
    footer:{
        position:"absolute", 
        left:0, 
        right:0, 
        bottom:20, 
        width:"100%", 
        flexDirection:"row",
    },
    price:{
        fontWeight:600, 
        fontSize:14,
        lineHeight:17.15
    },
    quantity:{
        fontWeight:400, 
        fontSize:10,
        lineHeight:14
    }
}