export const stylesHeader = {
    title:{
        marginTop:64,
        marginLeft:"22.5%"
    },
    text:{
        textAlign:"center",
        width:380,
        marginTop:24,
        marginLeft:10,
        fontSize:14,
      },
    input:{
        width:368,
        height:40,
        borderRadius:10,
        marginLeft:10,
        marginTop:24,
        borderWidth:2,
        paddingLeft:24
  },
    icon:{
        marginTop:-31.75,
        marginLeft:347.75,
  }
}