export const stylesCardWhite = {
    card:{
        borderColor:"#bbb",
        backgroundColor:"#fff",
    },
    title:{
        color:"#1c1c1c"
    },
    description:{
        color:"#1c1c1c"
    },

    minus:{
        color:"#1c1c1c"
    },
    cost:{
        color:"#1c1c1c"
    },
    plus:{
        color:"#1c1c1c"
    },
    amount:{
        backgroundColor:"#fff"
    },
    amountText:{
        color:"#1c1c1c"
    },
    button:{
        backgroundColor:"#fff",
    }
}