export const stylesCardDark = {
    card:{
        backgroundColor:"#222222",
        borderColor:"#555555"
    },
    title:{
        color:"#fff"
    },
    description:{
        color:"#fff"
    },
    button:{
        color:"#fff",
        backgroundColor:"#555555"
    },
    minus:{
        color:"#fff"
    },
    cost:{
        color:"#fff"
    },
    plus:{
        color:"#fff"
    },
    amount:{
        backgroundColor:"#555555"
    },
    amountText:{
        color:"#fff"
    }
}