export const stylesCard = {
    card:{
        width:368,
        marginTop:18,
        marginLeft:10,
        borderRadius:10,
        borderWidth:2
    },
    title:{
        fontWeight:600, 
        fontSize:14, 
        lineHeight:17.15, 
        marginTop:16, 
        marginLeft:16
    },
    description:{
        fontWeight:400, 
        fontSize:14, 
        marginTop:16, 
        marginLeft:16
    },
    button:{
        height:40, 
        borderRadius:10, 
        display:"flex", 
        alignItems:"center", 
        flexDirection:"row", 
        justifyContent:"space-around", 
        margin:16
    },
    buttonContent:{
        height:"100%", 
        width:55.5, 
        alignItems:"center", 
        marginTop:11
    },
    buttonText:{
        fontWeight:400, 
        fontSize:20, 
    },
    cost:{
        fontWeight:400, 
        fontSize:16
    },
    amount:{
        justifyContent:'center', 
        alignItems:'center',
        borderRadius:10,
        borderWidth:2,
        borderColor:"#ff7a00",
        width:38,
        height:40,
        marginLeft:167, 
        marginBottom:16,
    },
    amountText:{
        fontWeight:600, 
        fontSize:16
    },
    
}